// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddSubscrbe: typeof import('./src/components/AddSubscrbe/index.vue')['default']
    AddSubscribe: typeof import('./src/components/SubscribeCard/addSubscribe.vue')['default']
    ContentCard: typeof import('./src/components/ContentCard/index.vue')['default']
    ContentsCard: typeof import('./src/components/ContentsCard/index.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTree: typeof import('element-plus/es')['ElTree']
    FavoritesCard: typeof import('./src/components/FavoritesCard/index.vue')['default']
    FeedCard: typeof import('./src/components/FeedCard/index.vue')['default']
    Sbc: typeof import('./src/components/sbc/index.vue')['default']
    SearchBar: typeof import('./src/components/SearchBar/index.vue')['default']
    SubscribeCard: typeof import('./src/components/SubscribeCard/index.vue')['default']
    TodoListCard: typeof import('./src/components/TodoListCard/index.vue')['default']
    Undefined: typeof import('./src/components/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
    vPopover: typeof import('element-plus/es')['ElPopoverDirective']
  }
}
